import { FaqItem, DocumentItem, SiteConfig } from '../types';

export const initialSiteConfig: SiteConfig = {
  mainColor: '#1A3B6B', // Matte Navy
  accentColor: '#2E7D5B', // Deep Administrative Green
  warnColor: '#D97736', // Warm Dull Orange
  heroTitle: '계명대학교 한국어학당 가이드',
  heroSubtitle: '출결, 비자, 기숙사 생활 등 자주 묻는 질문을 검색해 보세요.',
  searchPlaceholder: '비자 연장, 출석 기준, 기숙사 외박 등을 검색해 보세요',
  bgType: 'color',
  // Logo Design Defaults
  logoType: 'none',
  logoText: '계명대학교',
  logoSubText: 'KEIMYUNG UNIVERSITY',
  logoTextColor: '#1A3B6B',
  logoFontWeight: 'bold',
  logoUrl: '',
  logoHeight: 40,
  logoSymbolIcon: 'university',
  // Popup Notice Defaults
  popupEnabled: true,
  popupTitle: '2026학년도 가을학기 비자(D-4) 연장 및 체류 관리 안내',
  popupBadge: '중요 공지',
  popupContent: '계명대학교 한국어학당 유학생 여러분의 안정적인 체류를 위해 비자 연장 신청 기간 및 출석 기준을 공지합니다.\n\n1. 체류기간 만료일 4개월 전부터 관할 출입국 사전 방문예약 또는 하이코리아 전자민원 신청이 필수입니다.\n2. 직전 학기 출석률 80% 미만 시 비자 연장이 제한될 수 있으니 출결 관리에 각별히 유의하시기 바랍니다.\n3. 문의: 국제처 외국인학생지원팀 (동영관 101호 / 053-580-6923)',
  popupColor: '#1A3B6B',
  popupStyle: 'modal',
  popupIcon: 'bell',
  popupLinkText: '비자 연장 서식 다운로드 바로가기',
  popupLinkTab: 'downloads',
  // Search Button & Bar Design Defaults
  searchButtonText: '검색',
  searchButtonSize: 'md',
  searchButtonShape: 'rounded',
  searchButtonRadius: 6,
  searchButtonColor: '',
  searchButtonShowIcon: true,
  searchButtonIconType: 'search',
  searchBarRadius: 8,
  fontSize: 'standard',
  fontFamily: 'noto',
  fontSizeScale: 'standard',
  fontHeadingWeight: 'bold',
  fontLineHeight: 'normal',
  borderRadius: 6,
  officeHours: '평일 09:00 ~ 17:00 (점심시간 12:00 ~ 13:00 / 주말·공휴일 휴무)',
  phone: '053-580-6923 ~ 6924 (국제사업센터)',
  email: 'kmu_intl@kmu.ac.kr',
  location: '대구광역시 달서구 달구벌대로 1095 계명대학교 성서캠퍼스 동영관(Dongyeong Hall) 101호 국제처',
  showInstagram: true,
  showYoutube: true,
  instagramUrl: 'https://www.instagram.com/keimyung_university',
  youtubeUrl: 'https://www.youtube.com/@KeimyungUniversity',
  // Related Websites for International Students
  showRelatedSites: true,
  relatedSites: [
    {
      id: 'hikorea',
      name: '하이코리아',
      nameEn: 'Hi Korea',
      url: 'https://www.hikorea.go.kr',
      badge: '출입국 민원',
      desc: '대한민국 전자정부 외국인종합안내포털 (체류기간 연장, 외국인등록증)',
    },
    {
      id: 'topik',
      name: '한국어능력시험 (TOPIK)',
      nameEn: 'TOPIK',
      url: 'https://www.topik.go.kr',
      badge: '한국어 평가',
      desc: '국립국제교육원 TOPIK 공식 접수 및 성적증명서 발급',
    },
    {
      id: 'studyinkorea',
      name: '스터디인코리아',
      nameEn: 'Study in Korea',
      url: 'https://www.studyinkorea.go.kr',
      badge: '유학 포털',
      desc: '교육부 국립국제교육원 한국유학 종합 시스템 및 정부초청장학금(GKS)',
    },
    {
      id: 'socinet',
      name: '사회통합정보망 (소시넷)',
      nameEn: 'Soci-Net',
      url: 'https://www.socinet.go.kr',
      badge: '이민자 통합',
      desc: '법무부 이민자 사회통합프로그램(KIIP) 및 조기적응프로그램 신청',
    },
    {
      id: 'immigration',
      name: '대구출입국·외국인사무소',
      nameEn: 'Daegu Immigration',
      url: 'https://www.immigration.go.kr',
      badge: '관할 출입국',
      desc: '대구광역시 동구 신서로 115 관할 출입국 및 사전방문예약 안내',
    },
  ],
  categories: [
    {
      id: 'attendance',
      name: {
        ko: '출결/수업',
        en: 'Attendance & Class',
        vi: 'Điểm danh & Lớp học',
        zh: '出勤/课程',
      },
      icon: 'CalendarCheck',
    },
    {
      id: 'visa',
      name: {
        ko: '비자/체류',
        en: 'Visa & Stay',
        vi: 'Visa & Lưu trú',
        zh: '签证/居留',
      },
      icon: 'FileBadge',
    },
    {
      id: 'dormitory',
      name: {
        ko: '기숙사',
        en: 'Dormitory',
        vi: 'Ký túc xá',
        zh: '宿舍',
      },
      icon: 'Building2',
    },
    {
      id: 'admin',
      name: {
        ko: '행정/증명서',
        en: 'Admin & Forms',
        vi: 'Hành chính & Hồ sơ',
        zh: '行政/证明',
      },
      icon: 'ScrollText',
    },
    {
      id: 'life',
      name: {
        ko: '유학생활',
        en: 'Campus Life',
        vi: 'Đời sống du học',
        zh: '留学生活',
      },
      icon: 'GraduationCap',
    },
  ],
  // Academic Calendar Settings (현재 학기 정보 설정)
  currentAcademicYear: 2026,
  currentAcademicTerm: 'spring',
  // Chatbot Settings Defaults
  chatbotEnabled: true,
  chatbotName: '계명어학당 안내 챗봇',
  chatbotSubtitle: 'FAQ·서식·학사일정 실시간 안내',
  chatbotWelcomeMsg: '안녕하세요! 계명대학교 한국어학당 안내 챗봇입니다. 🎓\n관리자가 등록한 자주 묻는 질문(FAQ), 행정 서식 자료, 한국어학당 학사일정을 바탕으로 정확하게 안내해 드립니다. 궁금한 점을 질문해 보세요!',
  chatbotPlaceholder: '질문을 입력하세요... (예: D-4 연장 서류, 출석률 기준, 일정)',
  chatbotColor: '#1A3B6B',
  chatbotBadgeText: '등록 정보 기반 안내',
  chatbotSuggestions: [
    'D-4 비자 연장에 필요한 서류는 무엇인가요?',
    '수료 및 비자 연장을 위한 최소 출석률은?',
    '2026학년도 한국어학당 학사 일정 알려주세요',
    '외국인 유학생 아르바이트(시간제 취업) 가능한가요?',
    '국제처 행정실(동영관 101호) 위치와 운영시간은?',
  ],
  chatbotNoMatchMsg: '문의하신 내용과 일치하는 공식 FAQ 및 행정 등록 정보가 현재 없습니다. 정확한 안내를 위해 담당 선생님께 1:1 빠른 문의를 남겨주시면 신속히 답변해 드리겠습니다.',
  chatbotShowInquiryOnNoMatch: true,
  // 1:1 Quick Inquiry Settings Defaults
  inquiryEnabled: true,
  inquiryTitle: '1:1 빠른 문의 접수',
  inquirySubtitle: '한국어학당 학사 및 비자 등 궁금한 점을 남겨주시면 담당 선생님이 확인 후 신속히 연락드립니다.',
  inquiryBadgeText: '',
  inquiryNotice: '',
  inquiryStudentIdLabel: '학번',
  inquiryStudentIdPlaceholder: '학번 8~10자리 숫자 입력 (예: 20241234)',
  inquiryNameLabel: '성명',
  inquiryNamePlaceholder: '외국인등록증 또는 여권상 영문/한글 성명',
  inquiryPhoneLabel: '연락처 (전화/메신저)',
  inquiryPhonePlaceholder: '예: 010-1234-5678, 카톡 ID',
  inquiryContentLabel: '문의 내용',
  inquiryContentPlaceholder: '비자 연장, 출결, 기숙사, 서류 등 궁금하신 사항을 자세히 적어주세요.',
  inquiryMinLength: 10,
  inquiryMaxLength: 1000,
  inquiryEnableQuiz: true,
  inquiryPrivacyNotice: '개인정보 수집 및 이용 안내: 수집항목(학번, 성명, 문의내용)은 1:1 학사 행정 상담 및 답변 처리를 위해서만 이용되며, 관련 법령에 따라 안전하게 보관됩니다.',
  inquiryPrivacyConsentText: '개인정보 수집 및 이용에 동의합니다.',
  inquirySuccessTitle: '문의가 정상적으로 접수되었습니다!',
  inquirySuccessDesc: '담당 선생님이 내용을 확인한 후 학번 또는 행정 시스템에 등록된 연락처로 신속히 답변해 드리겠습니다.',
  inquiryPausedNotice: '현재 행정실 사정으로 1:1 빠른 문의 온라인 접수가 일시 중단되었습니다. 급한 용무는 행정실(동영관 101호)로 전화 또는 방문 문의 바랍니다.',
};

// No automatic mock posts or documents - only admin uploaded items
export const initialFaqs: FaqItem[] = [];

export const initialDocuments: DocumentItem[] = [];

